const DEVICES = [
  {
    id: "E1001",
    name: "reTerminal E1001",
    description: '7.5" monochrome ePaper display',
    image: "assets/devices/reterminal-e1001.jpg",
    imageAlt: "reTerminal E1001 product photo",
    specs: [
      '7.5" display',
      "Monochrome",
      "4-level grayscale",
    ],
  },
  {
    id: "E1002",
    name: "reTerminal E1002",
    description: '7.3" full-color ePaper display',
    image: "assets/devices/reterminal-e1002.jpg",
    imageAlt: "reTerminal E1002 product photo",
    specs: [
      '7.3" display',
      "Full color",
      "E Ink Spectra 6",
    ],
  },
  {
    id: "E1003",
    name: "reTerminal E1003",
    description: '10.3" touch ePaper dashboard display',
    image: "assets/devices/reterminal-e1003.jpg",
    imageAlt: "reTerminal E1003 product photo",
    specs: [
      '10.3" display',
      "16-level grayscale",
      "Touch",
    ],
  },
  {
    id: "E1004",
    name: "reTerminal E1004",
    description: '13.3" full-color ePaper display',
    image: "assets/devices/reterminal-e1004.jpg",
    imageAlt: "reTerminal E1004 product photo",
    specs: [
      '13.3" display',
      "Full color",
      "E Ink Spectra 6",
    ],
  },
];

const PLATFORM_GROUPS = [
  {
    id: "official",
    title: "Official Platforms",
    description: "Start from supported ecosystem firmware and product workflows.",
  },
  {
    id: "base",
    title: "Base",
    description: "Use hardware bring-up demos to verify core device behavior first.",
  },
  {
    id: "community",
    title: "Community Projects",
    description: "Explore contributed examples that build on the official device stack.",
  },
];

const PLATFORM_CARDS = [
  {
    id: "base",
    group: "base",
    name: "Base",
    tagline: "Product bring-up demos for first-time hardware checks.",
    description:
      "Use Base firmware when you want to verify core hardware quickly: RTC, low-power mode, microphone recording, touch, and display behavior.",
    logo: "assets/platforms/base-logo.svg",
    preview: "assets/platforms/base-preview.svg?v=20260604-platform-art",
    previewAlt: "Basic firmware setup preview",
    accent: "#004966",
    highlight: "#8FC31F",
    supportedDevices: ["E1001", "E1002", "E1003", "E1004"],
    installReady: true,
    bullets: [
      "Fast product smoke tests",
      "No ecosystem account required",
      "Good starting point before advanced integrations",
    ],
    versions: [
      {
        version: "1.0.0",
        label: "Stable",
      },
    ],
    configFields: [],
    firmwareOptions: [
      {
        id: "RTC_PCF8563",
        name: "RTC Clock Demo",
        description: "Read and write the onboard PCF8563 real-time clock.",
        category: "Peripheral",
        compatible: ["E1001", "E1002", "E1003", "E1004"],
        notes: [
          { type: "warning", text: "Install a CR1220 coin cell battery in the RTC slot before flashing — without it, the clock resets every time the board loses power." },
          { type: "info", text: "First flash: the firmware automatically writes the build timestamp to the RTC. Subsequent reboots: the stored time is preserved (battery must be installed). The clock prints every second on Serial1 (GPIO43 TX, 115200 baud)." },
        ],
      },
      {
        id: "LowPower_DeepSleep",
        name: "Deep Sleep Demo",
        description: "Enter ESP32-S3 deep sleep and wake on button press.",
        category: "Power",
        compatible: ["E1001", "E1002", "E1003", "E1004"],
      },
      {
        id: "MicRecordToSD_E1001",
        name: "Microphone Recording",
        description: "Records audio from the onboard PDM microphone and saves it as a WAV file on the MicroSD card. Press the green KEY0 button once to start recording; press it again to stop. The LED blinks while recording is in progress.",
        category: "Audio",
        compatible: ["E1001", "E1002"],
      },
      {
        id: "MicRecordToSD_E1003",
        name: "Microphone Recording",
        description: "Records audio from the onboard PDM microphone and saves it as a WAV file on the MicroSD card. Press the green KEY0 button once to start recording; press it again to stop. The LED blinks while recording is in progress.",
        category: "Audio",
        compatible: ["E1003"],
      },
      {
        id: "E1003_TouchDraw",
        name: "Touch Draw",
        description: "Draw dots on the E1003 ePaper display from touch input.",
        category: "Display",
        compatible: ["E1003"],
      },
      {
        id: "LED_Control_E1001",
        name: "LED Blink Demo",
        description: "Toggle the onboard LED with 1-second intervals.",
        category: "Peripheral",
        compatible: ["E1001", "E1002"],
      },
      {
        id: "LED_Control_E1003",
        name: "LED Blink Demo",
        description: "Toggle the onboard LED with 1-second intervals.",
        category: "Peripheral",
        compatible: ["E1003"],
      },
      {
        id: "LED_Control_E1004",
        name: "LED Blink Demo",
        description: "Toggle the onboard LED with 1-second intervals.",
        category: "Peripheral",
        compatible: ["E1004"],
      },
      {
        id: "Buzzer_Control",
        name: "Buzzer Alert Demo",
        description: "Play basic alert tones: single beep, double beep, and alarm.",
        category: "Peripheral",
        compatible: ["E1001", "E1002", "E1003", "E1004"],
      },
      {
        id: "Buzzer_Music",
        name: "Buzzer Music Tones",
        description: "Play musical note arpeggios using the onboard buzzer.",
        category: "Peripheral",
        compatible: ["E1001", "E1002", "E1003", "E1004"],
      },
      {
        id: "UserButtons",
        name: "Button Press Demo",
        description: "Detect and report presses on all three user buttons.",
        category: "Peripheral",
        compatible: ["E1001", "E1002", "E1003", "E1004"],
      },
      {
        id: "Battery_Monitor",
        name: "Battery Voltage Monitor",
        description: "Read and display the battery voltage via ADC.",
        category: "Power",
        compatible: ["E1001", "E1002", "E1003", "E1004"],
      },
      {
        id: "MicroSD_ListFiles",
        name: "MicroSD File Listing",
        description: "Mount the MicroSD card and list files to serial output.",
        category: "Peripheral",
        compatible: ["E1001", "E1002", "E1003", "E1004"],
      },
      {
        id: "GxEPD2_reTerminal_E1001",
        name: "Display Demo (GxEPD2)",
        description: "Six-screen B&W demo: splash, system info, typography, geometry, patterns, dashboard.",
        category: "Display",
        compatible: ["E1001"],
      },
      {
        id: "GxEPD2_reTerminal_E1002",
        name: "Color Display Demo (GxEPD2)",
        description: "Six-screen 6-color demo showcasing the full color palette and patterns.",
        category: "Display",
        compatible: ["E1002"],
      },
      {
        id: "GxEPD2_reTerminal_E1003",
        name: "Display Demo (GxEPD2)",
        description: "Six-screen monochrome demo optimized for the 10.3\" 1872x1404 panel.",
        category: "Display",
        compatible: ["E1003"],
      },
      {
        id: "GxEPD2_reTerminal_E1004",
        name: "Color Display Demo (GxEPD2)",
        description: "Six-screen 6-color demo for the 13.3\" dual-chip Spectra 6 panel.",
        category: "Display",
        compatible: ["E1004"],
      },
      {
        id: "GxEPD2_reTerminal_E1001_Gray4",
        name: "4-Level Grayscale Demo (Adafruit GFX)",
        description: "Four grayscale bands and concentric circles on the E1001 panel. Uses Adafruit_GFX canvas with raw SPI register access.",
        category: "Display",
        compatible: ["E1001"],
      },
      {
        id: "Seeed_GFX_E1001_Gray4",
        name: "4-Level Grayscale Demo (Seeed GFX)",
        description: "Four horizontal grayscale bands on the E1001 panel using the Seeed_GFX / TFT_eSPI high-level EPaper API.",
        category: "Display",
        compatible: ["E1001"],
      },
      {
        id: "GxEPD2_reTerminal_E1003_Gray16",
        name: "16-Level Grayscale Demo",
        description: "Sixteen grayscale bands and gradient bar on the E1003 IT8951 panel.",
        category: "Display",
        compatible: ["E1003"],
      },
      {
        id: "SHT4x_Sensor",
        name: "Temperature & Humidity Sensor",
        description: "Read temperature and humidity from the SHT40 sensor via I2C every 5 seconds.",
        category: "Peripheral",
        compatible: ["E1001", "E1002", "E1003", "E1004"],
        notes: [
          { type: "info", text: "An SHT40 sensor must be connected to the I2C Grove port (SDA=GPIO19, SCL=GPIO20). Readings print every 5 seconds on Serial1 (GPIO43 TX, 115200 baud)." },
        ],
      },
      {
        id: "SD_ImagePipeline_E1001_BW",
        name: "SD Image Display (B&W)",
        description: "Load a JPEG/PNG from MicroSD and render it on the E1001 panel with dithering.",
        category: "Display",
        compatible: ["E1001"],
        configFields: [
          { id: "cfgImagePath", nvsKey: "imagePath", nvsType: "string", label: "Image file path", type: "text", defaultValue: "/img/demo.jpg", placeholder: "/img/demo.jpg" },
          { id: "cfgDither", nvsKey: "dither", nvsType: "i32", label: "Dithering algorithm", type: "select", defaultValue: 2, options: [{ value: 0, label: "None" }, { value: 1, label: "Bayer 8x8" }, { value: 2, label: "Floyd-Steinberg" }, { value: 3, label: "Jarvis-Judice-Ninke" }, { value: 4, label: "Atkinson" }] },
          { id: "cfgGamma", nvsKey: "gamma", nvsType: "float", label: "Gamma correction", type: "number", defaultValue: 1.0, min: 0.1, max: 3.0, step: 0.1 },
          { id: "cfgInvert", nvsKey: "invert", nvsType: "u8", label: "Invert black/white", type: "checkbox", defaultValue: 0 },
          { id: "cfgAnchor", nvsKey: "anchor", nvsType: "i32", label: "Image position", type: "select", defaultValue: 4, options: [{ value: 0, label: "Top-Left" }, { value: 1, label: "Top-Center" }, { value: 2, label: "Top-Right" }, { value: 3, label: "Middle-Left" }, { value: 4, label: "Center" }, { value: 5, label: "Middle-Right" }, { value: 6, label: "Bottom-Left" }, { value: 7, label: "Bottom-Center" }, { value: 8, label: "Bottom-Right" }] },
          { id: "cfgFitMode", nvsKey: "fitMode", nvsType: "i32", label: "Scaling mode", type: "select", defaultValue: 2, options: [{ value: 0, label: "Original size" }, { value: 1, label: "Fit to screen" }, { value: 2, label: "Custom scale" }] },
          { id: "cfgScale", nvsKey: "scale", nvsType: "float", label: "Scale factor", type: "number", defaultValue: 0.7, min: 0.1, max: 2.0, step: 0.1 },
        ],
        notes: [
          { type: "warning", text: "Place a JPEG or PNG image at /img/demo.jpg on the MicroSD card before flashing." },
          { type: "info", text: "Supports Floyd-Steinberg, Bayer, Jarvis, and Atkinson dithering. Configure before flashing in Firmware Hub." },
        ],
      },
      {
        id: "SD_ImagePipeline_E1001_Gray4",
        name: "SD Image Display (4-Gray)",
        description: "Load a JPEG/PNG from MicroSD and render it in 4-level grayscale on the E1001 panel.",
        category: "Display",
        compatible: ["E1001"],
        configFields: [
          { id: "cfgImagePath", nvsKey: "imagePath", nvsType: "string", label: "Image file path", type: "text", defaultValue: "/img/demo.jpg", placeholder: "/img/demo.jpg" },
          { id: "cfgDither", nvsKey: "dither", nvsType: "i32", label: "Dithering algorithm", type: "select", defaultValue: 2, options: [{ value: 0, label: "None" }, { value: 1, label: "Bayer 8x8" }, { value: 2, label: "Floyd-Steinberg" }, { value: 3, label: "Jarvis-Judice-Ninke" }, { value: 4, label: "Atkinson" }] },
          { id: "cfgGamma", nvsKey: "gamma", nvsType: "float", label: "Gamma correction", type: "number", defaultValue: 1.0, min: 0.1, max: 3.0, step: 0.1 },
          { id: "cfgAnchor", nvsKey: "anchor", nvsType: "i32", label: "Image position", type: "select", defaultValue: 4, options: [{ value: 0, label: "Top-Left" }, { value: 1, label: "Top-Center" }, { value: 2, label: "Top-Right" }, { value: 3, label: "Middle-Left" }, { value: 4, label: "Center" }, { value: 5, label: "Middle-Right" }, { value: 6, label: "Bottom-Left" }, { value: 7, label: "Bottom-Center" }, { value: 8, label: "Bottom-Right" }] },
          { id: "cfgFitMode", nvsKey: "fitMode", nvsType: "i32", label: "Scaling mode", type: "select", defaultValue: 2, options: [{ value: 0, label: "Original size" }, { value: 1, label: "Fit to screen" }, { value: 2, label: "Custom scale" }] },
          { id: "cfgScale", nvsKey: "scale", nvsType: "float", label: "Scale factor", type: "number", defaultValue: 0.7, min: 0.1, max: 2.0, step: 0.1 },
        ],
        notes: [
          { type: "warning", text: "Place a JPEG or PNG image at /img/demo.jpg on the MicroSD card before flashing." },
        ],
      },
      {
        id: "SD_ImagePipeline_E1002",
        name: "SD Image Display (Color)",
        description: "Load a JPEG/PNG from MicroSD and render it in 6-color on the E1002 Spectra 6 panel.",
        category: "Display",
        compatible: ["E1002"],
        configFields: [
          { id: "cfgImagePath", nvsKey: "imagePath", nvsType: "string", label: "Image file path", type: "text", defaultValue: "/img/demo.jpg", placeholder: "/img/demo.jpg" },
          { id: "cfgDither", nvsKey: "dither", nvsType: "i32", label: "Dithering algorithm", type: "select", defaultValue: 2, options: [{ value: 0, label: "None" }, { value: 1, label: "Bayer 8x8" }, { value: 2, label: "Floyd-Steinberg" }, { value: 3, label: "Jarvis-Judice-Ninke" }, { value: 4, label: "Atkinson" }] },
          { id: "cfgGamma", nvsKey: "gamma", nvsType: "float", label: "Gamma correction", type: "number", defaultValue: 1.0, min: 0.1, max: 3.0, step: 0.1 },
          { id: "cfgAnchor", nvsKey: "anchor", nvsType: "i32", label: "Image position", type: "select", defaultValue: 4, options: [{ value: 0, label: "Top-Left" }, { value: 1, label: "Top-Center" }, { value: 2, label: "Top-Right" }, { value: 3, label: "Middle-Left" }, { value: 4, label: "Center" }, { value: 5, label: "Middle-Right" }, { value: 6, label: "Bottom-Left" }, { value: 7, label: "Bottom-Center" }, { value: 8, label: "Bottom-Right" }] },
          { id: "cfgFitMode", nvsKey: "fitMode", nvsType: "i32", label: "Scaling mode", type: "select", defaultValue: 2, options: [{ value: 0, label: "Original size" }, { value: 1, label: "Fit to screen" }, { value: 2, label: "Custom scale" }] },
          { id: "cfgScale", nvsKey: "scale", nvsType: "float", label: "Scale factor", type: "number", defaultValue: 0.7, min: 0.1, max: 2.0, step: 0.1 },
        ],
        notes: [
          { type: "warning", text: "Place a JPEG or PNG image at /img/demo.jpg on the MicroSD card before flashing." },
        ],
      },
      {
        id: "SD_ImagePipeline_E1003",
        name: "SD Image Display (16-Gray)",
        description: "Load a JPEG/PNG from MicroSD and render it in 16-level grayscale on the E1003 panel.",
        category: "Display",
        compatible: ["E1003"],
        configFields: [
          { id: "cfgImagePath", nvsKey: "imagePath", nvsType: "string", label: "Image file path", type: "text", defaultValue: "/img/demo.jpg", placeholder: "/img/demo.jpg" },
          { id: "cfgDither", nvsKey: "dither", nvsType: "i32", label: "Dithering algorithm", type: "select", defaultValue: 2, options: [{ value: 0, label: "None" }, { value: 1, label: "Bayer 8x8" }, { value: 2, label: "Floyd-Steinberg" }, { value: 3, label: "Jarvis-Judice-Ninke" }, { value: 4, label: "Atkinson" }] },
          { id: "cfgGamma", nvsKey: "gamma", nvsType: "float", label: "Gamma correction", type: "number", defaultValue: 1.0, min: 0.1, max: 3.0, step: 0.1 },
          { id: "cfgAnchor", nvsKey: "anchor", nvsType: "i32", label: "Image position", type: "select", defaultValue: 4, options: [{ value: 0, label: "Top-Left" }, { value: 1, label: "Top-Center" }, { value: 2, label: "Top-Right" }, { value: 3, label: "Middle-Left" }, { value: 4, label: "Center" }, { value: 5, label: "Middle-Right" }, { value: 6, label: "Bottom-Left" }, { value: 7, label: "Bottom-Center" }, { value: 8, label: "Bottom-Right" }] },
          { id: "cfgFitMode", nvsKey: "fitMode", nvsType: "i32", label: "Scaling mode", type: "select", defaultValue: 0, options: [{ value: 0, label: "Original size" }, { value: 1, label: "Fit to screen" }, { value: 2, label: "Custom scale" }] },
          { id: "cfgScale", nvsKey: "scale", nvsType: "float", label: "Scale factor", type: "number", defaultValue: 1.0, min: 0.1, max: 2.0, step: 0.1 },
        ],
        notes: [
          { type: "warning", text: "Place a JPEG or PNG image at /img/demo.jpg on the MicroSD card before flashing." },
        ],
      },
      {
        id: "SD_ImagePipeline_E1004",
        name: "SD Image Display (Color)",
        description: "Load a JPEG/PNG from MicroSD and render it in 6-color on the E1004 Spectra 6 panel.",
        category: "Display",
        compatible: ["E1004"],
        configFields: [
          { id: "cfgImagePath", nvsKey: "imagePath", nvsType: "string", label: "Image file path", type: "text", defaultValue: "/img/demo.jpg", placeholder: "/img/demo.jpg" },
          { id: "cfgDither", nvsKey: "dither", nvsType: "i32", label: "Dithering algorithm", type: "select", defaultValue: 1, options: [{ value: 0, label: "None" }, { value: 1, label: "Bayer 8x8" }, { value: 2, label: "Floyd-Steinberg" }, { value: 3, label: "Jarvis-Judice-Ninke" }, { value: 4, label: "Atkinson" }] },
          { id: "cfgGamma", nvsKey: "gamma", nvsType: "float", label: "Gamma correction", type: "number", defaultValue: 1.0, min: 0.1, max: 3.0, step: 0.1 },
          { id: "cfgAnchor", nvsKey: "anchor", nvsType: "i32", label: "Image position", type: "select", defaultValue: 4, options: [{ value: 0, label: "Top-Left" }, { value: 1, label: "Top-Center" }, { value: 2, label: "Top-Right" }, { value: 3, label: "Middle-Left" }, { value: 4, label: "Center" }, { value: 5, label: "Middle-Right" }, { value: 6, label: "Bottom-Left" }, { value: 7, label: "Bottom-Center" }, { value: 8, label: "Bottom-Right" }] },
          { id: "cfgFitMode", nvsKey: "fitMode", nvsType: "i32", label: "Scaling mode", type: "select", defaultValue: 0, options: [{ value: 0, label: "Original size" }, { value: 1, label: "Fit to screen" }, { value: 2, label: "Custom scale" }] },
          { id: "cfgScale", nvsKey: "scale", nvsType: "float", label: "Scale factor", type: "number", defaultValue: 1.0, min: 0.1, max: 2.0, step: 0.1 },
        ],
        notes: [
          { type: "warning", text: "Place a JPEG or PNG image at /img/demo.jpg on the MicroSD card before flashing." },
        ],
      },
    ],
  },
  {
    id: "esphome",
    group: "official",
    name: "ESPHome",
    tagline: "Smart-home firmware with YAML setup and Home Assistant integration.",
    source: {
      label: "Official website",
      url: "https://esphome.io/",
    },
    description:
      "ESPHome turns microcontroller boards into local smart-home devices using simple YAML configuration, web tools, and Home Assistant workflows.",
    logo: "assets/platforms/esphome-logo-card.png",
    preview: "assets/platforms/esphome-preview-enhanced.png",
    previewAlt: "ESPHome dashboard preview",
    accent: "#004966",
    highlight: "#8FC31F",
    supportedDevices: ["E1001", "E1002", "E1003"],
    installReady: false,
    bullets: [
      "Home Assistant friendly",
      "Wi-Fi provisioning expected",
      "Good for dashboards, sensors, and local automation",
    ],
    versions: [
      {
        version: "2026.5.2",
        label: "Preview",
      },
    ],
    configFields: [
      {
        id: "wifiSsid",
        label: "Wi-Fi SSID",
        type: "text",
        placeholder: "Office Wi-Fi",
      },
      {
        id: "wifiPassword",
        label: "Wi-Fi password",
        type: "password",
        placeholder: "Stored locally before flashing",
      },
    ],
    firmwareOptions: [],
  },
  {
    id: "squareline",
    group: "official",
    name: "SquareLine Vision",
    tagline: "Visual UI workflow for embedded screen experiences.",
    source: {
      label: "Official website",
      url: "https://app.vision.squareline.io/",
    },
    description:
      "SquareLine Vision focuses on designing embedded interfaces visually, then preparing UI assets and implementation output for screen-based products.",
    logo: "assets/platforms/squareline-logo.png",
    preview: "assets/platforms/squareline-preview-43.png",
    previewAlt: "SquareLine Vision product preview",
    accent: "#004966",
    highlight: "#8FC31F",
    supportedDevices: ["E1002", "E1003"],
    installReady: false,
    bullets: [
      "Visual UI design workflow",
      "Useful for screen-first product demos",
      "Best with display-capable devices",
    ],
    versions: [
      {
        version: "1.3.0",
        label: "Preview",
      },
    ],
    configFields: [],
    firmwareOptions: [],
  },
  {
    id: "opendisplay",
    group: "official",
    name: "OpenDisplay",
    tagline: "Open-source ePaper firmware and protocol for BLE display control.",
    source: {
      label: "Official website",
      url: "https://www.opendisplay.org/",
    },
    description:
      "OpenDisplay provides firmware and browser tools for low-power ePaper display projects, including BLE control, configuration, and image upload flows.",
    logo: "assets/platforms/opendisplay-logo-card-v2.png",
    preview: "assets/platforms/opendisplay-screen-enhanced.png",
    previewAlt: "OpenDisplay browser upload flow",
    accent: "#004966",
    highlight: "#8FC31F",
    supportedDevices: ["E1001", "E1002", "E1003"],
    installReady: false,
    bullets: [
      "BLE-oriented ePaper control",
      "Browser-based configuration and image upload",
      "Good for always-on information panels",
    ],
    versions: [
      {
        version: "0.1.0",
        label: "Preview",
      },
    ],
    configFields: [],
    firmwareOptions: [],
  },
  {
    id: "voice-memo-reminder",
    group: "community",
    name: "Voice Memo Reminder",
    tagline: "Community AI voice memo project for ePaper reminder lists.",
    author: "limengdu",
    source: {
      label: "limengdu/ePaper-Voice-Memo",
      url: "https://github.com/limengdu/ePaper-Voice-Memo",
    },
    description:
      "Voice Memo Reminder records a spoken memo, sends it to Groq Whisper and Llama 3.3, then turns it into a sorted ePaper reminder list.",
    logo: "assets/brand/reterminal-epaper-icon.svg",
    preview: "assets/devices/reterminal-e1003.jpg",
    previewAlt: "reTerminal E1003 running an ePaper reminder workflow",
    accent: "#004966",
    highlight: "#8FC31F",
    supportedDevices: ["E1001", "E1002", "E1003"],
    installReady: true,
    bullets: [
      "Community project",
      "Voice-to-reminder workflow",
      "Requires Wi-Fi and a Groq API key",
    ],
    versions: [
      {
        version: "1.0.0",
        label: "Stable",
      },
    ],
    configFields: [],
    firmwareOptions: [
      {
        id: "ePaper_VoiceMemo_E1001",
        name: "Voice Memo Reminder",
        description: "AI-powered voice memo to ePaper reminder list. Hold KEY0 to record, release to create a sorted to-do item via Groq Whisper + Llama 3.3.",
        category: "Application",
        compatible: ["E1001"],
        configFields: [
          { id: "cfgWifiSsid", nvsKey: "wifiSsid", nvsType: "string", label: "Wi-Fi SSID", type: "text", defaultValue: "", placeholder: "Your Wi-Fi network name" },
          { id: "cfgWifiPass", nvsKey: "wifiPass", nvsType: "string", label: "Wi-Fi Password", type: "text", defaultValue: "", placeholder: "Your Wi-Fi password" },
          { id: "cfgApiKey", nvsKey: "apiKey", nvsType: "string", label: "Groq API Key", type: "text", defaultValue: "", placeholder: "gsk_..." },
        ],
        notes: [
          { type: "warning", text: "Requires a free Groq API key. Get one at https://console.groq.com — the free tier includes Whisper and Llama 3.3." },
          { type: "info", text: "Hold KEY0 to record (up to 20s), release to process. Reminders persist across reboots via NVS. The screen auto-refreshes every 5 minutes." },
        ],
      },
      {
        id: "ePaper_VoiceMemo_E1002",
        name: "Voice Memo Reminder",
        description: "AI-powered voice memo to ePaper reminder list. Hold KEY0 to record, release to create a sorted to-do item via Groq Whisper + Llama 3.3.",
        category: "Application",
        compatible: ["E1002"],
        configFields: [
          { id: "cfgWifiSsid", nvsKey: "wifiSsid", nvsType: "string", label: "Wi-Fi SSID", type: "text", defaultValue: "", placeholder: "Your Wi-Fi network name" },
          { id: "cfgWifiPass", nvsKey: "wifiPass", nvsType: "string", label: "Wi-Fi Password", type: "text", defaultValue: "", placeholder: "Your Wi-Fi password" },
          { id: "cfgApiKey", nvsKey: "apiKey", nvsType: "string", label: "Groq API Key", type: "text", defaultValue: "", placeholder: "gsk_..." },
        ],
        notes: [
          { type: "warning", text: "Requires a free Groq API key. Get one at https://console.groq.com — the free tier includes Whisper and Llama 3.3." },
          { type: "info", text: "Hold KEY0 to record (up to 20s), release to process. Reminders persist across reboots via NVS. The screen auto-refreshes every 5 minutes." },
        ],
      },
      {
        id: "ePaper_VoiceMemo_E1003",
        name: "Voice Memo Reminder",
        description: "AI-powered voice memo to ePaper reminder list with touch checkboxes. Hold KEY0 to record, tap checkboxes to mark items done.",
        category: "Application",
        compatible: ["E1003"],
        configFields: [
          { id: "cfgWifiSsid", nvsKey: "wifiSsid", nvsType: "string", label: "Wi-Fi SSID", type: "text", defaultValue: "", placeholder: "Your Wi-Fi network name" },
          { id: "cfgWifiPass", nvsKey: "wifiPass", nvsType: "string", label: "Wi-Fi Password", type: "text", defaultValue: "", placeholder: "Your Wi-Fi password" },
          { id: "cfgApiKey", nvsKey: "apiKey", nvsType: "string", label: "Groq API Key", type: "text", defaultValue: "", placeholder: "gsk_..." },
        ],
        notes: [
          { type: "warning", text: "Requires a free Groq API key. Get one at https://console.groq.com — the free tier includes Whisper and Llama 3.3." },
          { type: "info", text: "Hold KEY0 to record (up to 20s), release to process. Tap a checkbox to mark it done. Reminders persist across reboots. The screen auto-refreshes every 5 minutes." },
        ],
      },
      {
        id: "ePaper_VoiceMemo_E1003_ZH",
        name: "Voice Memo Reminder (Chinese)",
        description: "Chinese language voice memo reminder with embedded TrueType font rendering. Hold KEY0 to record in Chinese, tap checkboxes to mark items done.",
        category: "Application",
        compatible: ["E1003"],
        configFields: [
          { id: "cfgWifiSsid", nvsKey: "wifiSsid", nvsType: "string", label: "Wi-Fi SSID", type: "text", defaultValue: "", placeholder: "Your Wi-Fi network name" },
          { id: "cfgWifiPass", nvsKey: "wifiPass", nvsType: "string", label: "Wi-Fi Password", type: "text", defaultValue: "", placeholder: "Your Wi-Fi password" },
          { id: "cfgApiKey", nvsKey: "apiKey", nvsType: "string", label: "Groq API Key", type: "text", defaultValue: "", placeholder: "gsk_..." },
        ],
        notes: [
          { type: "warning", text: "Requires a free Groq API key. Get one at https://console.groq.com — the free tier includes Whisper and Llama 3.3." },
          { type: "info", text: "This firmware includes an embedded Chinese TrueType font (~800KB). It renders Chinese text natively via OpenFontRender." },
        ],
      },
    ],
  },
];
