[platformio]
default_envs = reterminal_e1001

[env]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
upload_speed = 115200
monitor_speed = 115200
board_build.arduino.memory_type = qio_opi
lib_deps =
    https://github.com/Seeed-Studio/Seeed_GFX
    lvgl/lvgl@^9.2.0
build_flags =
    -D BOARD_HAS_PSRAM
    -D LV_CONF_INCLUDE_SIMPLE
    -I include

[env:reterminal_e1001]
build_flags =
    ${env.build_flags}
    -D RETERMINAL_E1001
    -D EPAPER_LVGL_HOR_RES=800
    -D EPAPER_LVGL_VER_RES=480

[env:reterminal_e1002]
build_flags =
    ${env.build_flags}
    -D RETERMINAL_E1002
    -D EPAPER_LVGL_HOR_RES=800
    -D EPAPER_LVGL_VER_RES=480

[env:reterminal_e1003]
build_flags =
    ${env.build_flags}
    -D RETERMINAL_E1003
    -D EPAPER_LVGL_HOR_RES=1872
    -D EPAPER_LVGL_VER_RES=1404

[env:reterminal_e1004]
build_flags =
    ${env.build_flags}
    -D RETERMINAL_E1004
    -D EPAPER_LVGL_HOR_RES=1200
    -D EPAPER_LVGL_VER_RES=1600
